### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by Elation-Z** [mxyooR/Mys_Goods_Gui#1]
作者您好，我按您的“安装与运行”步骤来做，我电脑预装了python和node.js，第二步设置Python虚拟环境并安装依赖时，pip install -r requirements.txt这条命令并不能生效，因为当前目录Mys_Goods_Gui目录下并没有requirements.txt，然后我看见requirements.txt在flask_app目录下面，我就只能先cd flask_app，再执行pip install -r requirements.txt。但是我执行完成后并没有出现electron文件夹，也就是说cd electron 无效，Mys_Goods_Gui和flask_app目录下也从没有过electron文件夹，因此我并不清楚要在哪个位置执行npm install.我就在flask_app目录下执行的话，附图是执行的结果，一直失败，您有什么头绪吗？
![QQ图片20240725201611](https://github.com/user-attachments/assets/9390708e-966d-41e6-8e29-f388a4ffd460)

**Comment by mxyooR** [comment]
在主目录下npm install

**Comment by mxyooR** [comment]
如果自用的话flask环境部署好就行了

**Comment by mxyooR** [comment]
electron只是套个外壳好看点

**Comment by mxyooR** [comment]
flask环境部署好厚运行app.py 然后在浏览器打开127.0.0.1:5000

**Comment by mxyooR** [comment]
改了下readme

**Comment by Elation-Z** [comment]
我尝试在不运行npm install的情况下，直接在flask_app下运行python app.py，并访问地址，点击侧边栏开始运行后，报了如下错误：AttributeError: 'PyPNGImage' object has no attribute 'resize'，附图是详情
![1](https://github.com/user-attachments/assets/501ebfef-9862-48ee-8342-73bfb7411603)
![2](https://github.com/user-attachments/assets/c6a94d0d-ec78-4fce-8bf8-3b12493e4996)

**Comment by Elation-Z** [comment]
抱歉刚刚点错了，我尝试在不运行npm install 的情况下，在flask_app下直接运行python app.py，并访问对应地址，点击侧栏的开始运行，报了如下错误：AttributeError: 'PyPNGImage' object has no attribute 'resize'，详情在附图
![1](https://github.com/user-attachments/assets/46217da1-21c0-41a0-8014-3b96104b96aa)
![2](https://github.com/user-attachments/assets/657a0741-3677-478e-906e-75eda6e2fc45)

**Comment by mxyooR** [comment]
你qrcode的版本是7.4.2的吗

**Comment by Elation-Z** [comment]
是的
![3](https://github.com/user-attachments/assets/d399bb62-94bb-4c7d-8325-1357d04df65a)

**Comment by mxyooR** [comment]
这样 把调整大小放前端，把getuserinfo.html和login.py改一下
![QQ_1721957589079](https://github.com/user-attachments/assets/99239f6e-796c-4c65-9b42-878e30b1061b)
![QQ_1721957617207](https://github.com/user-attachments/assets/a9c01a8a-fb38-4507-a7c7-e7eb72ea05c8)

**Comment by Elation-Z** [comment]
好的，已经可以正常操作了，顺便问一下这个目前不支持多账号是吗，我试了一下在第一个账号登陆上之后，用另一个账号再登录就显示登陆失败

**Comment by mxyooR** [comment]
不支持多账号 但是可以切换账号就是重新用另外一个账号扫二维码登录

**Comment by Elation-Z** [comment]
好的，感谢作者大大
