### ISSUE TITLE
普通用户的问题

### ISSUE THREAD

**Issue by maple7leaf** [mxyooR/Mys_Goods_Gui#2]
不知道为什么，前几天刚下的时候运行正常，今天突然就不行了，刚开始是这个问题

**Comment by maple7leaf** [comment]
![f18af74c48b212e5dd55d62d1816250](https://github.com/user-attachments/assets/cac22f92-eccc-42da-bebc-60cc01b99779)

**Comment by maple7leaf** [comment]
后面又一直登录失败
![屏幕截图 2024-07-31 172626](https://github.com/user-attachments/assets/1f73acfd-cad9-41b5-b2b8-350d11354cec)

**Comment by maple7leaf** [comment]
麻烦大大看到指点一下

**Comment by mxyooR** [comment]
崩铁更新了二维码登录要改最近会改

**Comment by mxyooR** [comment]
可以用源代码暂时修复的方案 release版本还没改

**Comment by maple7leaf** [comment]
不是很懂，我昨天登录是显示原神登录，今天改崩铁了

**Comment by maple7leaf** [comment]
我是纯小白

**Comment by mxyooR** [comment]
昨天如果登录成功了的今天不用登录了能正确获取地址就行

**Comment by maple7leaf** [comment]
我昨天登录创建任务完，今天运行卡死了，时间一动不动，然后关了重新开就啥都没了

**Comment by mxyooR** [comment]
把托盘里面的也关了 按理来说config应该还在的 如果急用的话把代码clone下来本地跑一下

**Comment by maple7leaf** [comment]
我看看怎么弄

**Comment by maple7leaf** [comment]
OK，也是成功放弃了。下载代码弄好了，到本地运行实在不会了

**Comment by mxyooR** [comment]
已更新

**Comment by maple7leaf** [comment]
好耶

**Comment by guilaile666** [comment]
![M~F}{VOC{HCUT(N4`8R 8U9](https://github.com/user-attachments/assets/05f2e515-b749-45a8-aa7e-4091df2e5f1b)
作者请问一下，我这个失败是次数设置太多，还是单纯的运气不好

**Comment by guilaile666** [comment]
![L{7V`Y(VJ_CH7B$UTUB)661](https://github.com/user-attachments/assets/9106f7c6-79d7-4baa-9df7-ca9e1d41ab2a)
![53XHA(IN)K5ODY8GY2J3C%W](https://github.com/user-attachments/assets/92be4f88-e2e6-4a82-a975-59a3a16f5ba0)
![M~F}{VOC{HCUT(N4`8R 8U9](https://github.com/user-attachments/assets/c8021523-2b79-428d-a1a6-e6de07e59635)
cd /d E:\Scientific Internet Access\mys-goods-gui-win32-x64\resources\app\flask_app
python app.py

cd /d E:\Scientific Internet Access\mys-goods-gui-win32-x64\resources\app
npm start
以上运行代码附上图片，作者请问一下，我这个失败是设置有问题，还是单纯的运气不好

**Comment by guilaile666** [comment]
> ![L{7VY(VJ_CH7B$UTUB)661](https://github.com/user-attachments/assets/9106f7c6-79d7-4baa-9df7-ca9e1d41ab2a) ![53XHA(IN)K5ODY8GY2J3C%W](https://github.com/user-attachments/assets/92be4f88-e2e6-4a82-a975-59a3a16f5ba0) ![M~F}{VOC{HCUT(N48R 8U9](https://private-user-images.githubusercontent.com/170833798/358853109-c8021523-2b79-428d-a1a6-e6de07e59635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDc1MDAsIm5iZiI6MTcyMzkwNzIwMCwicGF0aCI6Ii8xNzA4MzM3OTgvMzU4ODUzMTA5LWM4MDIxNTIzLTJiNzktNDI4ZC1hMWE2LWU2ZGUwN2U1OTYzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNTA2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDY4YTFhZmE0MTExMzVhM2QwZDVlN2QyMzQwMTRjMmY4MTMxOTg5NDI1YzVhMGQ4MjgxYWM0ODI4MWQyZDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k9R3TUH3CulHEc5JWHNE5ZFyTRgfZkgizI0sdyH6uDM)cd /d E：\Scientific Internet Access\mys-goods-gui-win32-x64\resources\app\flask_app python app.py
> 
> cd /d E：\Scientific Internet Access\mys-goods-gui-win32-x64\resources\app npm start 以上运行代码附上图片，作者请问一下，我这个失败是设置有问题，还是单纯的运气不好

**Comment by guilaile666** [comment]
> > ![L{7VY(VJ_CH7B$UTUB)661](https://private-user-images.githubusercontent.com/170833798/358853099-9106f7c6-79d7-4baa-9df7-ca9e1d41ab2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDc1ODAsIm5iZiI6MTcyMzkwNzI4MCwicGF0aCI6Ii8xNzA4MzM3OTgvMzU4ODUzMDk5LTkxMDZmN2M2LTc5ZDctNGJhYS05ZGY3LWNhOWUxZDQxYWIyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNTA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGM2ZWE5NjYyOTQxYWZiN2QxN2RkMDdkNjZhYTVjNmRmODRiMTNmNjRiNGQwYmU5N2E2M2IyNGNhZGM4NWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GgPFxfXE2kAtDQKEQ26CAf6sR_KcveA02Z9rCLVUOcQ) ![53XHA(IN)K5ODY8GY2J3C%W](https://private-user-images.githubusercontent.com/170833798/358853105-92be4f88-e2e6-4a82-a975-59a3a16f5ba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDc1ODAsIm5iZiI6MTcyMzkwNzI4MCwicGF0aCI6Ii8xNzA4MzM3OTgvMzU4ODUzMTA1LTkyYmU0Zjg4LWUyZTYtNGE4Mi1hOTc1LTU5YTNhMTZmNWJhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNTA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODEyODNiZTZhNDRkNTA2YWE1M2VlMjlmZjVmZjk5ZjlmNmE4ZGZhOTE1NmQ4OWMwOTI3NTA0ODhmNWUwNDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ol9OWHuOrnaiTKclSwYypwZ8vWHm_YqDlI1nH_ozBl8) ![M~F}{VOC{HCUT（N48R 8U9](https://private-user-images.githubusercontent.com/170833798/358853109-c8021523-2b79-428d-a1a6-e6de07e59635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDc1MDAsIm5iZiI6MTcyMzkwNzIwMCwicGF0aCI6Ii8xNzA4MzM3OTgvMzU4ODUzMTA5LWM4MDIxNTIzLTJiNzktNDI4ZC1hMWE2LWU2ZGUwN2U1OTYzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QxNTA2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDY4YTFhZmE0MTExMzVhM2QwZDVlN2QyMzQwMTRjMmY4MTMxOTg5NDI1YzVhMGQ4MjgxYWM0ODI4MWQyZDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k9R3TUH3CulHEc5JWHNE5ZFyTRgfZkgizI0sdyH6uDM)cd /d E：\Scientific Internet Access\mys-goods-gui-win32-x64\resources\app\flask_app python app.py
> > cd /d E：\Scientific Internet Access\mys-goods-gui-win32-x64\resources\app npm start 以上运行代码附上图片，作者请问一下，我这个失败是设置有问题，还是单纯的运气不好

登录显示是成功的

**Comment by mxyooR** [comment]
应该是运气不好

**Comment by mxyooR** [comment]
等有空写个c++的估计会快点

**Comment by guilaile666** [comment]
> 应该是运气不好

我还以为是部署出问题了
