### ISSUE TITLE
获取商品列表的兑换时间不对

### ISSUE THREAD

**Issue by Yoimiya-993** [mxyooR/Mys_Goods_Gui#4]
原石明明今天就能兑换，但它显示的是下一次兑换时间，新建任务时也是这个时间
![image](https://github.com/user-attachments/assets/c643d1e9-d342-4e6b-9bdb-ed88b1871b7d)

**Comment by Yoimiya-993** [comment]
![image](https://github.com/user-attachments/assets/dc62284a-e8ed-4c19-b93d-a7eab59e15fe)
还有新建任务这里无法修改，修改任何一项都保存失败，虽然弹窗提示是“任务创建成功”。
（就比如先把任务清空，然后新建任务里改任意一个输入框后保存，任务还是空的）
日志里提示缺失必要参数
![image](https://github.com/user-attachments/assets/09f8191d-e01e-4538-a76c-88b64c745c18)

**Comment by mxyooR** [comment]
> ![image](https://private-user-images.githubusercontent.com/52495231/362111307-dc62284a-e8ed-4c19-b93d-a7eab59e15fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzExMTIsIm5iZiI6MTcyNDgzMDgxMiwicGF0aCI6Ii81MjQ5NTIzMS8zNjIxMTEzMDctZGM2MjI4NGEtZThlZC00YzE5LWI5M2QtYTdlYWI1OWUxNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MTYxN2UxMmY1MjY0Y2ZmZTZlMGM5MjJmZTU1MWY3NjMwZTM2ZGQ3N2RlZjY0MzIwYTQ4ZDUwZjc2M2UzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2hyxdFMGj0kis5Nb5sY9gkJ55e1xg4KtxS_e61Ne2aA) 还有新建任务这里无法修改，修改任何一项都保存失败，虽然弹窗提示是“任务创建成功”。 （就比如先把任务清空，然后新建任务里改任意一个输入框后保存，任务还是空的） 日志里提示缺失必要参数 ![image](https://private-user-images.githubusercontent.com/52495231/362112256-09f8191d-e01e-4538-a76c-88b64c745c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzExMTIsIm5iZiI6MTcyNDgzMDgxMiwicGF0aCI6Ii81MjQ5NTIzMS8zNjIxMTIyNTYtMDlmODE5MWQtZTAxZS00NTM4LWE3NmMtODhiNjRjNzQ1YzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMzgyYjE4NWY2YmUxYjA4NDJlZjUxNmUxZGNiM2QyN2Q0YWYxZDNlMTJlODQyOGRhZDdjMDcwMWI2ZTE5YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HgGrMhkXDAa1NfIfO4mTJdp_qg3EEoSgmy2fKThx1bc)

这个问题应该是地址，先不要选空地址选你的实际地址我等会来改下

**Comment by Yoimiya-993** [comment]
> > ![image](https://private-user-images.githubusercontent.com/52495231/362111307-dc62284a-e8ed-4c19-b93d-a7eab59e15fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzExMTIsIm5iZiI6MTcyNDgzMDgxMiwicGF0aCI6Ii81MjQ5NTIzMS8zNjIxMTEzMDctZGM2MjI4NGEtZThlZC00YzE5LWI5M2QtYTdlYWI1OWUxNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MTYxN2UxMmY1MjY0Y2ZmZTZlMGM5MjJmZTU1MWY3NjMwZTM2ZGQ3N2RlZjY0MzIwYTQ4ZDUwZjc2M2UzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2hyxdFMGj0kis5Nb5sY9gkJ55e1xg4KtxS_e61Ne2aA) 还有新建任务这里无法修改，修改任何一项都保存失败，虽然弹窗提示是“任务创建成功”。 （就比如先把任务清空，然后新建任务里改任意一个输入框后保存，任务还是空的） 日志里提示缺失必要参数 ![image](https://private-user-images.githubusercontent.com/52495231/362112256-09f8191d-e01e-4538-a76c-88b64c745c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzExMTIsIm5iZiI6MTcyNDgzMDgxMiwicGF0aCI6Ii81MjQ5NTIzMS8zNjIxMTIyNTYtMDlmODE5MWQtZTAxZS00NTM4LWE3NmMtODhiNjRjNzQ1YzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA3NDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMzgyYjE4NWY2YmUxYjA4NDJlZjUxNmUxZGNiM2QyN2Q0YWYxZDNlMTJlODQyOGRhZDdjMDcwMWI2ZTE5YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HgGrMhkXDAa1NfIfO4mTJdp_qg3EEoSgmy2fKThx1bc)
> 
> 这个问题应该是地址，先不要选空地址选你的实际地址我等会来改下

确实是空地址的问题

**Comment by Yoimiya-993** [comment]
还发现一个bug：每次新建完一个任务后这个页面就没法继续编辑下一个任务了，点输入框只能删除文字无法打字，表示输入框聚焦状态的橙色边也没有了

要点左侧导航的“打开任务列表”再关掉，这个新建任务页面才能继续编辑

**Comment by mxyooR** [comment]
> 原石明明今天就能兑换，但它显示的是下一次兑换时间，新建任务时也是这个时间 ![image](https://private-user-images.githubusercontent.com/52495231/362110390-c643d1e9-d342-4e6b-9bdb-ed88b1871b7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzI1NzAsIm5iZiI6MTcyNDgzMjI3MCwicGF0aCI6Ii81MjQ5NTIzMS8zNjIxMTAzOTAtYzY0M2QxZTktZDM0Mi00ZTZiLTliZGItZWQ4OGIxODcxYjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMjU1ZjA1YTAzNTcwOWM0ZTFhOTJiZjgwOWQ1ZDZjZmNhYzU0ODc0ZjBlMGE1YWMzYzczMTQzN2VmMWNmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fFLbsc0QuCINMVj1mil3jHgKJmfEPyEk_Fx4M-v4UY)

这个你先改下时间吧 好像获取的数据有问题

**Comment by mxyooR** [comment]
就新建任务里面改下时间

**Comment by Yoimiya-993** [comment]
改了，今天要抢的都建好了

**Comment by Yoimiya-993** [comment]
![image](https://github.com/user-attachments/assets/6138c555-27da-47ed-8316-690106337672)
这是怎么回事

**Comment by mxyooR** [comment]
没绑定角色吧

**Comment by Yoimiya-993** [comment]
> 没绑定角色吧

扫码方式获取的个人信息，任务列表json里也有uid

**Comment by mxyooR** [comment]
应该是要在米游社里面绑一下
