### ISSUE TITLE
我太惨了

### ISSUE THREAD

**Issue by maple7leaf** [mxyooR/Mys_Goods_Gui#8]
从用到现在一次都没成功过
![屏幕截图 2024-11-22 175148](https://github.com/user-attachments/assets/12eee7a8-07b0-4095-be11-26d7a9ab8096)
![屏幕截图 2024-11-22 175244](https://github.com/user-attachments/assets/c6064646-0292-4436-b27b-e75dcf54601b)

**Comment by mxyooR** [comment]
漏cookie了

**Comment by mxyooR** [comment]
是不是没绑定角色

**Comment by maple7leaf** [comment]
我都是开始半小时左右才扫的码登陆


流枫似槿
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月23日(周六) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mxyooR/Mys_Goods_Gui] 我太惨了 (Issue #8)




 
是不是没绑定角色

**Comment by mxyooR** [comment]
第二张图片漏cookie了建议删掉 可能是米游社没有绑定角色去米游社选择区服绑定一下看看
